remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Kseniia Andreeva — Junior QA Engineer
tagline: I am interested in developing in the direction of test automation (currently self-studying automation tools; have experience writing UI tests using Playwright). Open to continuous learning and adopting new tools in my work.
description: Открыта к стажировкам и проектам.
